### ISSUE TITLE
Natychmiastowe dodawanie map i NPC przez narratorów / CDN?

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#17]
Narratorzy i radni mają obecnie dostęp do własnego, ukrytego repozytorium w którym opisane są wątki wszystkich postaci. Można by stworzyć zaraz obok kolejne repozytorium, widoczne dla wszystkich, w których będą zawarte NPC i mapy które narratorzy i radni chcą podmieniać.

Obecnie rozwiązanie jest na gitlabie (z racji darmowych repozytoriów prywatnych) więc repozytorium z mapami i NPC również by na nim było (zaraz obok by narratorzy nie musieli logować się na oddzielną stronę)

Plusy:
- Narratorzy nie muszą czekać kilka dni na dodanie jednego NPCa czy mapy na stałe.
- Jeżeli do dodatku dla narratorów dodamy możliwość wyświetlenia stworzonego pliku json z mapy na której jesteśmy to jest to najbliższe rozwiązanie postawionemu serwerowi który obsługuje jakąś bazę danych z npcami (a przy tym darmowe).

Mogę tym się zająć, potrzebuję tylko zielonego światełka.

**Comment by KrisAphalon** [comment]
1. To tylko było odniesienie że inne repozytorium które jest jakby w tej samej "organizacji" jest prywatne i dlatego tam widziałbym coś do czego również te same osoby by miały mozliwość edycji (narratorzy i radni), tyle że jako repozytorium otwarte.

2. Nie wiem szczerze, jednak po przeczytaniu tego co piszesz nie może być gorzej :p Do tego zmiany nie muszą być natychmiastowe przecież, tylko po prostu takowe nie będą wymagały dodatkowej twojej interwencji a z tego co widzę to rawgit jednakowo traktuje githuba i gitalaba i to po jego stronie zapewne jest ewentualny długi czas potrzebny do wczytania (nie wiem czy z obrazkami wgl trzeba go stosować)

**Comment by akrzyz** [comment]
Chcesz się bawić w coś takiego to proszę bardzo. Najpierw jednak skończ jedną rzecz zanim zabierzesz się za następną, ja wciąż czekam na jakąś wersje tego dodatku dla narratorów ;)

A co do tego pomysłu, to rozumiem, że trzeba by po prostu zasysać plik z dodatkowego źródła? Jeżeli tak to brzmi prosto a to czym to źródło będzie to już mi rybka.

**Comment by KrisAphalon** [comment]
Niby nie trzeba, ale niezalecane jest używanie linków wprost. W sumie istnieje https://raw.githack.com/ który daje pliki na CloudFlare z automatu... To chyba będzie najłatwiejsze rozwiązanie narazie.

No i wiem z tym dla narratorów, widziałeś postępy, teraz coś stanęło z przerzucaniem tego ;x

**Comment by KrisAphalon** [comment]
Dodatek przeniesiony na: https://github.com/nerthus-margonem/nerthusaddon
W razie kontynuowania pomysłu należy założyć issue tam
