### ISSUE TITLE
Boczny panel z zmianami na mapie

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#18]
Można by dodać jakiś dodatkowy, boczny panel, możliwe że wysuwany za pomocą przycisku czy coś w tym stylu zawierający dane o zmianach w danej mapie dodawanych przez narratorów/radnych, na podobnej zasadzie co mapy na stałe (osoby folder z plikami typu json z id mapy). Jedyne co to nie jestem pewien jak dokładnie miałoby coś takiego graficznie wyglądać od strony klienta.

**Comment by akrzyz** [comment]
Ja też nie wiem, na razie zmiany dokonywane przez moderatorów za pomocą poleceń na czacie są logowane w konsoli. Jak dla mnie póki co to wystarczy ale jakby miało się mocno to rozbudować to faktycznie można o czymś takim pomyśleć.

**Comment by KrisAphalon** [comment]
Nie chodzi o zmiany dokonywane przez moderatorów w danej jednej chwili, a raczej skróty akcji pisane przez moderatorów które opisują zmiany na mapce (jak np. spaloną ławkę czy niecodzienne zachowanie mieszkańcow) już kilka godzin/dni po akcji, tak by było to wiadome dla ludzi którzy na akcji nie byli

**Comment by akrzyz** [comment]
Mhm takie coś. Powiem szczerze, że nie wierze w utrzymywalność tego rozwiązania. Nie wierze, że narratorzy będą to uzupełniać i czyścić, na moje oko skończy się to tak ze ktoś coś napisze i będzie to wisieć nie wiadomo jak długo..

**Comment by KrisAphalon** [comment]
Już istnieje repozytorium ze zmianami, ale tylko dla narratorów (z wiadomościami dotyczącymi wątków, do których zwykły gracz nie powinien mieć dostępu) i jest ono regularnie uzupełniane (ostatnie wpisy w kolejnych dniach: 3dni, 5dni, 6dni, tydzień, 3x 2 tygodnie temu itd.). Więc myślę że jeżeli ktoś będzie miał czas na ustawianie NPCów to tym bardziej będzie mieć czas na wstawienie kilku zdań do jednego pliku. Całość można podłączyć też pod te zewnętrzne repozytorium narratorów (o którym mówiłem w #17).

Dodatkowo jak ktoś zauważy że dane są przeterminowane będzie mógł napisać o tym do narratora albo zgłosić issue na tamtym repozytorium.

**Comment by KrisAphalon** [comment]
Strona ze zmianami dostępna będzie jako link w nowym panelu: #58
Dalsze działania zostaną ewentualnie podjęte jak funkcyjni zdecydują się naprawdę regularnie go uzupełniać.
Na razie zamykam.
