### ISSUE TITLE
rawgit is dead

### ISSUE THREAD

**Issue by akrzyz** [akrzyz/nerthusaddon#24]
Move addon to different CDN as rawgit is not working anymore. This require changes in NN_start.js and global addon update. 
Jsdeliver is an option to replace rawgit or find some real deployment server. 
Without this changes future addon releases are blocked!

**Comment by KrisAphalon** [comment]
#25

**Comment by akrzyz** [comment]
Udało się przerzucić wszystko na jsdelivr. Jest jednak problem z ustawieniem linku do globalnego dodatku jako url do jsdelivr. Na razie jest zrobiona jest proteza ale trzeba to będzie jeszcze wyjaśnić.
