### ISSUE TITLE
Wersja przeglądarki na jaką dodatek jest pisany

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#32]
Warto by było gdzieś zawrzeć minimalne wymagania dodatku co do wersji najczęściej używanych przeglądarek. Wtedy nie będzie problemu z używaniem nowych rozwiązań, które mogą nie pasować do starszych przeglądarek. Bardziej by była to informacja dla edytorów jeżeli by chcieli skorzystać z jakiejś funkcji która może wydawać się nowa.

**Comment by akrzyz** [comment]
Powiem szczerze, że nie wiem. Margo to raczej nie jest gra w którą się gra mając najnowszy sprzęt, często ludzie grają w pracy na jakiś szmelcach które mają jeszcze windowsa XP albo używają jakiś dziwnych przeglądarek typu safari albo ie. Ciężko mi jest określić co ma być wspierane a co nie.

**Comment by KrisAphalon** [comment]
Samo margonem nie pomaga w tym:
http://support.garmory.pl/s/margonem.pl/pl/21/149/problemy-z-gra/jakie-sa-wymagania-gry

Możemy jedynie się dowiedzieć że IE powinno być również obsługiwane.
Ja bym był obecnie za tym by było to podporządkowane IE 11, to jest zawierało es5 i wstecz:
http://kangax.github.io/compat-table/es5/
oraz let i const z es6
http://kangax.github.io/compat-table/es6/
wraz z kilkoma dodatkowymi rzeczami z tej strony.

IE 11 to i tak stara przeglądarka, a większość i tak zapewne gra na chromie czy mozilli.
Najlepszym rozwiązaniem by był pewnie osobny kod dla IE i osobny dla innych przeglądarek które obecnie zostawiły IE daleko w tyle, ale raczej nie potrzebne na razie coś takiego.

**Comment by KrisAphalon** [comment]
Ogólnie to nawet na SI jest border-image zastosowany przez twórców, a on działa dopiero w IE 11 więc na 100% nie warto wcześniejszych wersji wspierać.
https://caniuse.com/#search=Border%20images

**Comment by KrisAphalon** [comment]
Dodany zostanie babel do #79 co rozwiąże problem potrzeby pisania starego kodu

**Comment by KrisAphalon** [comment]
Dodałem wsparcie IE w 2e8857391d9645f31a32700ba7fe895f7dcc6747 i chciałem przetestować, czy działa. Ku mojemu zdziwieniu po wejściu na maszynę wirtualną, sama gra nie działa na IE11. Nie działają przyciski na nowej stronie głównej, a jak hackowatym sposobem udało mi się zalogować i wejść do gry to przywitały mnie takie errory (bez żadnych dodatków): 
![gscreenshot_2020-06-30-005105](https://user-images.githubusercontent.com/25371882/86063719-cb1a8000-ba6b-11ea-961d-05a0a99f014b.png)
i nie udało mi się zacząć rozgrywki. Czyli IE kompletnie można wykluczyć ze wspierania. Zostawie babel chyba tak czy siak by możliwe było korzystanie z najnowszych nowinek języka a jednocześnie działało na np. starej wersji mozilli która na XP działa, bo na niej gra chyba jeszcze działa (choć nie miałem okazji stestować)

**Comment by KrisAphalon** [comment]
Dodatek przeniesiony na: https://github.com/nerthus-margonem/nerthusaddon
(oraz ten issue rozwiązany)
