### ISSUE TITLE
NI - co trzeba poprawić

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#34]
Jak na tą chwilę: wszystko. Dodatek w ogóle się nie wczytuje na NI.

Tak to:
Tarcza powinna być jako button taki jak np. konfiguracja.
Komendy powinny ładnie wyglądać.
Okienko konfiguracji tak samo.

lista niekompletna.

Ogólnie najpierw trzeba sprawdzić jak podłącza się dodatek pod NI - czy osobnym linkiem czy tym samym. (obecnie nie ma w ogóle podłączonego) Wtedy będzie można stworzyć plan działania.

**Comment by KrisAphalon** [comment]
A jak wygląda podłączenie dodatku? Mogę poprzerabiać i popatrzyć jak to działa ale nie wiem czy możesz po prostu np. osobny link dać do dodatku na NI.

**Comment by KrisAphalon** [comment]
Dobra, po zainstalowaniu przez tempermonkey "działa" bez zarzutów. 

No prócz tego że 90% skryptów wywala bo API jest inne.

Teraz jeszcze raz pytanie, czy robimy z tego dwie różne ścieżki w zależności od SI/NI czy w każdym miejscu będzie podmienianie w zależności od tego czy jest to NI czy SI.

Bo w takim wypadku w starcie można sprawdzić jaki interfejs jest (jest ciasteczko o nazwie interfejs bodajże) i ustawić go jako zmienną, i potem w każdym miejscu dawać jeżeli si to to jeżeli ni to tamto.
 
Ta decyzja do ciebie należy chyba :v

**Comment by KrisAphalon** [comment]
Mam już zrobiony chat, jeszcze muszę ogarnąć *addGrafy i tak dalej. Da się zrobić wszystko :# Jutro (znaczy dziś) wieczorem dam pullrequesta

**Comment by akrzyz** [comment]
Ja się jeszcze nie przyglądałem jak działa NI od strony API ale zakładam, że większość kodu będzie wspólna tylko trzeba mieć jakiś klej porobionym który interakcje z samym API załatwi. 
Czekam na pull requesta bo mi się nie chce samemu API od NI rozkminiać ;p

**Comment by KrisAphalon** [comment]
To "API" jest straszne. Dodatkowo z podmianą mapy/npców trzeba będzie mocno kombinować, bo wszystko leci do jednego canvasa. Ale mam nadzieję że jakoś dam radę :#

**Comment by KrisAphalon** [comment]
Po kolejnych godzinach zmagań ogarnąłem kod na dodanie grafiki (który jest bardziej na podmianę mapy, tylko w nieco inny sposób. Po prostu grafika jest na mapie ale pod npcami). Przynajmniej w teorii. No i nie wygląda aż tak pięknie, bo wzorowałem się na już stworzonym dodatku (podobnie jak ze zmianą czatu. czytając kod NI można równie dobrze skoczyć z okna, szczególnie na moim obecnym poziomie jsa .-. (ale staram się ogarniać jak najwięcej))

Samej zmiany mapy bez takiego trochę "workaround-u" nie udało mi się osiągnąć.

NPCe najpewniej będzie się dodawało npcami. (jak patrzyłem to o wiele prościej chyba jest :#)
Weather najfajniej by było wbudowanymi `Engine.weather`, może one nie będą takie straszne
Light to bym poszedł po najmniejszej linii oporu i narzucił nad canvas płachtę przepuszczającą eventy i jedynie zmieniającą swoje opacity odwrotnie do lighta, np. `*light 0.3` by zmieniał opacity na 0.7, czyli by było bardzo czarnawo. Dodatkowo można dodać łatwo zmianę koloru lighta, bo czemu nie.

**Comment by akrzyz** [comment]
Zmieniłem start dodatku, teraz pluginy nigdy same się nie startują. Start wołany jest zawsze z NN_start.js niezależnie czy reszta wczytywana jest z localStorage czy z cdn'a.
Jeżeli jesteśmy na SI to na pluginach woła się `start` natomiast na NI woła się na nich `start_ni`. To powinno ładnie załatwić kwestie startowania dodatku na różnych silnikach, wystarczy adaptery ukryć w `start_ni`. Jeżeli moduł nie ma metody `start_ni` to po prostu nie będzie się nawet próbował uruchomić na NI.

**Comment by KrisAphalon** [comment]
Tyle że to nie takie proste, np. niektóre komendy osobno wymagają atencji, np. teraz jak piszę to w `nerthus.chatCmd.map["map"]` również potrzeba sprawdzenia czy to ni czy si, bo inaczej mapa jest wyświetlana. I jedno będzie miało g a drugie API

**Comment by KrisAphalon** [comment]
Chyba że chcesz bym definiował całe funkcje w tym start_nie

**Comment by akrzyz** [comment]
`nerthus.chatCmd.map["map"] ` jak komenda nie działa na NI to można ją wywalić z mapy w `starcie_ni`

**Comment by KrisAphalon** [comment]
Nie o to chodzi.
`nerthus.chatCmd.map["map"]` może działać na NI jak będzie mieć przełącznik w sobie, czyli będzie się różnie zachowywała w zależności od tego jaki jest interfejs (bo cała mapa jest w jednym canvasie na NI)

to teraz moje pytanie:
czy mam deklarować takie funkcje po prostu w start/start_ni?

**Comment by akrzyz** [comment]
możesz zrobić funkcje `nerthus.chatCmd.map_ni["map"] = ...` i w `start_ni` przemapować `this.map.map = this.map_ni.map` i powinno śmigać

**Comment by KrisAphalon** [comment]
Zrozumiałem jak zedytowałeś, tak zrobię

**Comment by akrzyz** [comment]
posiedziałem dzisiaj chwile i naskrobałem coś takiego: https://rawgit.com/akrzyz/margonem_addons/master/margo-prettifier.js (trzeba mieć chat z boku włączony żeby zadziałało) jeszcze sporo jest tam do zrobienia ale przynajmniej już jakoś zaczyna wyglądać :)

**Comment by KrisAphalon** [comment]
Co to jest? Bo nie mogę uzmysłowić sobie co ten kod robi. (jeżeli to 
> Jak się tak na to patrze to chyba wole wrócić do dopracowania starego dodatku, który by SI rozwijał na > cały ekran zamiast babrać się z NI.
To według mnie najwyżej w osobnym issue to pisz, a tak to zupełnie nie jest to rozwiązanie dla portu na NI .-.


Za to ja skończyłem już `*map` i wieczorem dam kolejnego pullrequesta. I może to dziwnie nieco wyglądać ale na 100% działa i nie mam pojęcia jak inaczej to zrobić, bo dostać się do rysowania mapy do canvasa jest baaaaardzo trudno, a API nie obsługuje czegoś takiego. Mam nadzieję że NPC będą łatwiejsze, nimi chyba się zajmę kolejnymi

**Comment by akrzyz** [comment]
Ciekaw jestem jak mapę zrobiłeś bo nie widziałem tam takiego obiektu jak w si `#ground` ale może niezbyt dokładnie patrzyłem.

Jak ogarniesz jak grafiki na mapie rozstawiać to będzie też duży krok w kierunku dodania światełek bo pogoda i noc będą raczej proste.

Ja w między czasie popatrzyłem się na penel i coś tam nadziergałem  #37.
Ikona z tarczą wygląda zaskakująco ładnie ale dodana jest na chama a nie za pomocą API, może potem poszukam jak to dodać we właściwy sposób. Nie wiem też czemu ale opcje się nie rozwijają na NI ale może je po prostu zrobię je zawsze widocznymi.

**Comment by KrisAphalon** [comment]
Trochę zarwanie głowy mam więc opóźnia to pracę we wdrożeniu (potrzebuję dostosować z mojej wersji testowej na gita i wtedy dokładnie przestestować czy działa. A testy Qunit są beznadziejne do testowania tego typu addonów, chyba że byśmy dali require (które jest z nodejsa a nie z testów i ogólnie działa samo w sobie okropnie i niezgodnie z przeznaczeniem tutaj, dlatego błędy wywala) całego engina margonem,a  potem całe okno zbudowalibyśmy.

Po zmianie mapek światełka można dodać w prawie ten sam sposób. Jedyne co to bym podpiął światełka i mapę pod jedną funkcję, bo nie wiem jak będą działać razem. A raczej światełka na mapkach podstawionych nie są pożądane, choć może. No nic, zobaczy się jak będzie to działać. A NPCe to osobna sprawa, bo oni muszą być jako postacie które za sobą się pojawiają itd. Więc mapie bliżej do świateł niż do postaci :#

Z tymi brzydkimi ustawieniami nie wiem czy warto się bawić z alertem, czy by nie zrobić całości od nowa, jakiś ładnych ustawień, ładnych linków pod grafikami jakimiś, by było to przyjemne a nie to co jest teraz :#
No ale to na pewno na dalszy plan

W dodawanie widgetów się jeszcze nie bawiłem, ale chyba było to dosyć proste, nie jestem pewien

**Comment by KrisAphalon** [comment]
99% zmian wdrożona w #35, zamykam, znalezione pojedyncze błędy do nowych issue.
