### ISSUE TITLE
Brak zmian w NN_Start.js po stronie klienta

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#40]
Trzeba zmienić link w http://serwery.margonem.pl/ by miał on w sobie najnowsze zmiany co do linków, bo obecnie wczytuje za każdym razem starą wersję, bez względu na to czy localstorage jest włączony czy nie.

**Comment by akrzyz** [comment]
Osz, nie zauważyłem że start się zmienił w tym pull request'cie, podmienię wieczorem.
