### ISSUE TITLE
Niepoprawne działanie wczytywania nowej wersji

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#42]
Kiedy wczytujemy starą wersję z localStorage, nowa wersja pliku `NN_start` z githuba nie zapisuje się 

[localStorage.getItem(nerthus) po bugu](https://pastebin.com/xYYYg1MC)
Należy zwrócić uwagę na nową wersję:
```
"version":"9fa78fb24bdff0e20a91c68d28e796cd478bbc08"
```
podczas gdy jednocześnie funkcje z NN_start są stare:
```js
"fileUrl":"(function(filename)\r\n{\r\n    return [[this.filesPrefix, this.version].join(this.version_separator), filename].join('/')\r\n})"
```
 (brak obecnego w wersji ```9fa78fb24bdff0e20a91c68d28e796cd478bbc08``` `encodeURI()`)

Dla porównania: [localStorage.getItem(nerthus) po kompletnym ręcznym usunięciu obiektu w localStoragu](https://pastebin.com/8UeHZiyB) 
Mimo tej samej wersji co wcześniej funkcja z NN_start jest już nowa:
```js
"fileUrl":"(function(filename)\r\n{\r\n    return encodeURI([[this.filesPrefix, this.version].join(this.version_separator), filename].join('/'))\r\n})"
```

Jednocześnie w obydwu przypadkach zmiany w innych plikach dobrze zaakceptowało (przykładowo zmiany w `mapsArr`), jedyne co to przez tego buga nie zmieniło znaków specjalnych na znaki do URI, więc większości osób nie działają teraz nowe mapy.

Jako rozwiązanie bym zapisywał wersję w osobnym localstoragu, i jego najpierw wczytywać. Jak się nie zgadza - usunąć wszystko i kazać pobrać aktualną wersję, usuwając przy tym po sobie śmieci.
O wiele prostsze to niż jakieś dziwne próby najpierw załadowania całego dodatku by dopiero wtedy sprawdzić wersję.

Dodatkowo (raczej nie ma to związku z tym błędem), 17sta linijka w NN_start:
```js
nerthus.addon.version = nerthus.addon.consts.MASTER
```
jest błędna, ponieważ nigdzie wcześniej nie ma deklaracji nerthus.addon.consts.MASTER, więc nerthus.addon.version pozostaje niezdefiniowany.

**Comment by akrzyz** [comment]
Pewnie nie zmieniłem wersji po zmianie NN_start.js, wtedy nie zkminia że trzeba nadpisać dodatek w stoage'u.. zaraz domerguje twojego pull requesta, zmienię wersje i powinno się naprawić.
