### ISSUE TITLE
try{}catch(){}

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#45]
Czy w każdym pliku potrzebne są `try{}catch(){}`? Jak będziemy mieli w danym pliku 100% code coverage można by pomyśleć nad usunięciem ich, jako że nie powinno być żadnych problemów. A jeżeli już to chyba nie takich, które by wywaliły error który by catch złapał.

**Comment by akrzyz** [comment]
W sumie są one reliktem z czasów jak nie było sprawdzani czy te pliki się w ogóle parsują. Teraz można je raczej w miarę bezpiecznie wywalić. Zajmę się tym w wolnej chwili.
