### ISSUE TITLE
Wyciekanie before() w test/npc_suite.js

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#46]
[test/npc_suite.js](https://github.com/akrzyz/nerthusaddon/blob/master/test/npc_suite.js) Jest źle napisany i wycieka `before()` naokoło, dlatego nie mogę np. dodać testów do [test/night_suite.js](https://github.com/akrzyz/nerthusaddon/blob/master/test/night_suite.js) bo wykrywa `before()` z npc_suite i nie mogę testować niczego w pliku.

[Z tego co patrzyłem](https://github.com/itaylor/qunit-mocha-ui) to w Mocha w interfejsie Qunit nie można robić tak jak jest teraz zrobione, to jest dać jedno `before` a potem kilka `suite`. Ja to bym podzielił to po prostu na pliki poszczególne, i w każdym w `before` wpisał tylko to, co jest potrzebne.

Jeżeli chcesz przetestować błąd to dodaj w teście w night-cie `console.log(nerthus)`, a ci wypisze obiekt który powstałby po `before` z npc_suite
Możesz też spojrzeć na 7e2b118fe016d3f0067ea426f1d1e172956f47c2 [tutaj](https://travis-ci.org/akrzyz/nerthusaddon/builds/503166248?utm_source=github_status&utm_medium=notification)

**Comment by akrzyz** [comment]
Też się już na to natknąłem. Może być before jeden główny ponad suitem ale nie spodziewałem się, że on jest dzielony między plikami z testami, myślałem że każdy plik jest wczytywany i puszczany z osobna a tu lipa, tak samo globale ciekną między plikami.
Rozwiązaniem jest zmienić sposób puszczania testów tak, żeby uruchamiać moche w pętli podając po jednym pliku i agregować wynik. Strasznie upierdliwe to jest ale jak znajdę lepszego rozwiązania to tak to przerobie.

**Comment by akrzyz** [comment]
Zmieniłem jak puszczają się testy, sprawdź czy to rozwiązało twój problem.

**Comment by KrisAphalon** [comment]
Działa, choć trochę średnie to rozwiązanie :# Ale problem rozwiązany
