### ISSUE TITLE
Dodatek niepoprawnie parsuje i zapisuje wyrażenia

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#51]
Wyrażenie które wygląda w ten sposób:
```js
nerthus.loadQueue = []
```
Jest parsowana przez dodatek na:
```js
(function() {
    [native code]
})
```
Przez co źle się wczytuje i uniemożliwia poprawne odczytanie dodatku z localstorage:
![asd](https://user-images.githubusercontent.com/25371882/54093104-48604400-4394-11e9-9357-64a037642f83.png)

**Comment by akrzyz** [comment]
To by było ciekawe bo konstrukcja obiekt.tablica = [ ] istnieje i jest poprawni parsowana w wielu miejscach, zwłaszcza w NN_dlaRadnych.js. Gdzie masz ten błąd?

**Comment by KrisAphalon** [comment]
```js
nerthus.defer = function(fun,data)
{
    if(typeof fun !== 'function')
        throw new TypeError('fun must be function when it is ' + typeof fun)
    g.loadQueue.push({'fun':fun, 'data':data})
}

nerthus.loadQueue = []
nerthus.loadOnEveryMap = function (fun, data)
{
    nerthus.loadQueue.push([fun, data])
}
nerthus.loadNewMapQueue = function ()
{

    for (const i in this.loadQueue)
    {
        this.loadQueue[i][0](this.loadQueue[i][1])
    }
}
```

**Comment by akrzyz** [comment]
To ja stawiam, że jak zapisujesz to ta kolejka nie jest pusta i to wyrażenie wcale nie wygląda tak jak pokazujesz.

**Comment by KrisAphalon** [comment]
No nie jest pusta, i nie chcę by była pusta, i muszą być w niej funkcje by działała poprawnie. Czyli w ogóle nie mogę zrobić czegoś takiego i zamiast prostej funkcji która mówi sama z siebie co robi za każdym razem mam monstrum pisać?

**Comment by akrzyz** [comment]
ale to ci nie zadziała bo thisa masz innego i go nie bindujesz do loadNewMapQueue

**Comment by KrisAphalon** [comment]
To dobrze działa. Nie działa zapisywanie.

**Comment by akrzyz** [comment]
jak na moje oko to nie powinieneś zapisywać tej kolejki jak nie jest pusta

**Comment by KrisAphalon** [comment]
To jak mam to zrobić by jej nie zapisywać jak zawsze ma być pełna a dodatek sam zapisuje się?
Bo obecnie nie widzę sposobu by zrobić ładną funkcję która robi to co chcę bo automatycznie dodatek ją zapisze, będzie [native code] i nie wczyta się.

**Comment by KrisAphalon** [comment]
Nw wgl czy zapisywanie dodatku ma sens jak istnieje coś takiego jak cache w obecnych czasach .-.

**Comment by akrzyz** [comment]
Przecież dodatek se zapisuje jak zassie nową wersje i jeszcze się nie wystartuje więc nie wiem czemu ta kolejka nie jest pusta

**Comment by KrisAphalon** [comment]
No to w takim razie też nie wiem, bo kolejka się powinna zapełniać dopiero przy kolejnych `start_ni`, a jak widać zapełnia się przed (?)

**Comment by akrzyz** [comment]
sprawdziłem i faktycznie zapisuje się po wystartowaniu, tylko nie wiem dlaczego i nie jestem pewien czy tak być powinno

**Comment by KrisAphalon** [comment]
Na pewno masz plik `NN_loader.js` w którym powtarzasz rzeczy z `NN_start.js` w jakiś dziwny sposób

**Comment by akrzyz** [comment]
Kiedyś chciałem podzielić starta ale z jakiegoś powodu zaniechałem i został ten loader, w sumie to nie pamiętam na czym to stanęło

**Comment by KrisAphalon** [comment]
To że zapisuje się po wystartowaniu wyjaśniałoby dlaczego wcześniej musiałem robić osobne zapisywanie dla NI i SI...

**Comment by akrzyz** [comment]
stawiam, że się tak zapisuje przez opcje a przynajmniej pamiętam, że były z nimi jakieś problemy. Pewnie da się to obejść i zapisywać przed wystartowaniem co ma sens. Jutro na to popatrzę.

**Comment by akrzyz** [comment]
Poprawiłem, wydaje się, że teraz powinno działaś. Po wczytaniu dodatku z nową wersją najpierw jest zapisywany a dopiero potem stratowany.

**Comment by KrisAphalon** [comment]
Chyba działa, zamykam w takim razie na tą chwilę.
