### ISSUE TITLE
Dostęp jako maintainer 

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#53]
Jako że trudno mi się skontaktować gdzie indziej, napisałem tutaj.
Będąc osobą, którą stworzyła cały dodatek na NI oraz regularnie wprowadza do niego wymagane poprawki, chciałbym prosić o możliwość zostania maintainerem głównego dodatku. Inne strony (to jest rada oraz administracja) nie widzą przeciwskazań do tego. Zgoda @akrzyz jest jedyną, którą potrzebuje.

Już nie raz pomagałem osobom ze świata w ich problemach technicznych. Do tego stworzyłem w pełni* działającą wersję dodatku na NI. Co więcej, stworzyłem również cały [dodatek dla narratorów](https://gitlab.com/Aphalon/narrator-tools), którego to teraz przepisuję na [webpacka](https://gitlab.com/Aphalon/narrator-tools/tree/webpack-test), z racji, że przerósł moje oczekiwania co do ilości funkcji. Myślę, że lepszej i bardziej zaangażowanej w dodatek osoby nie można znaleźć na tą funkcję.

Jako maintainer pierwszymi moimi krokami będzie wprowadzenie do głównego dodatku wszystkich zmian z #35 , które to działają prawie bez zarzutu na obu interfejsach, a w szczególności na SI, co do którego działa to lepiej i zawiera dodatkowe funkcje (jak ukrywanie npców zależne od mapy, jeżeli się id mapy wpisze w komendę czy też ukrywanie potworków z mapy jeżeli narrator odpowienio to ustawi, a jednocześnie gracz ma włączone to w ustawieniach), a także dodanie obsługi niektórych rzeczy, których nie mogłem dodać mając na uwadze, że są jednocześnie w użyciu dwie wersje dodatku.

Dodatkowo wszelkie znalezione błędy będą czym prędzej poprawiane, tak jak ostatnio znaleziony przeze mnie [błąd](https://github.com/KrisAphalon/nerthusaddon/commit/261bba58daffcb89aee31ed02315392b207433b6), który uniemożliwia ustawianie zwojów czerwonego smoka, mając zainstalowaną obecną wersję dodatku globalnego

Końcowym krokiem jest cały aspekt nowego dodatku, który to zapewne będzie po części przepisaniem obecnego systemu (najlepiej na coś pokroju webpacka) wraz z połączeniem go z serwerem, który tworzy @mikkielt, z którym się kontaktuje co do tego. To jednak zaplanowane jest na przyszłość.

**Comment by akrzyz** [comment]
Generalnie to spoko, mam na chwile obecną dwa warunki:
1. Dopisz trochę testów, bo na chwile obecną twój commit obniża pokrycie o 11%, dobij chociaż do 50%.
2. Staraj się dopisywać testy tak żeby pokrycie rosło a nie malało wraz z kolejnymi commitami.
Jak Nadrobisz to pokrycie na #35 to dodam Ci uprawnienia.

**Comment by KrisAphalon** [comment]
Pokrycie kodu który się wykonuje na SI jest większe niż u ciebie. Nie mogę napisać testów na rzeczy, które tak bardzo ingerują w silnik NI, bo to jest zupełnie bez sensu jak i tak co jakiś czas wychodzą bugi, bo Garmory coś zmieniło w silniku, a nie przez to, że skrypt jest niepoprawnie zrobiony. Jak mam napisać test który sprawdza, czy widget jest dodany poprawnie, kiedy to już trzeci raz mi wywala go czasem, bo Garmory coś zmieniło?

Mogę dodawać testy do rzeczy, które nie ingerują z silnikiem (obecnie plik worldEdit, choć nie wszystko do niego jeszcze leci i lepsze rozwiązanie znalazłem i stosuję w dodatku dla narów). Tak jak dodałem testy do parsowania komend.
Nie chcę dodawać testów do rzeczy, które mogą zmienić sposób w jaki powinny być robione.

% pokrycia jest według mnie złą statystyką dla kodu, który działa na innym kodzie który w każdej chwili może zostać zmieniony. Po to pisze się testy, by było wiadomo że coś działa albo nie działa. Jeżeli coś nie działa a testy przechodzą, to testy są bez sensu. A wiem że tak będzie jak zacznę je pisać do komunikacji dodatek-engine.

P.S.
Najnowsza wersja Engina na experimentalu nie wspiera już IE (zawiera `fetch` do komunikacji), więc komendy do NI również nie będą musiały polegać na antycznych ograniczeniach.

**Comment by akrzyz** [comment]
Generalnie testy do frontendu wydają mi się być upierdliwe kiedy spora część kodu ustawia jakieś pierdoły w html'owym dom'ie albo tak ja tutaj odwołuje się do czegoś z zewnątrz. No ale wewnętrznej logiki trochę tutaj jest i można ją przetestować.

Z tym % pokrycia kodu, to jakbyś kiedyś rozmawiał z jakimś managerem, to lepiej nie mów takich rzeczy na głos ;p

Zmergowanie #35 pozostawiam tobie jako wisienkę na torcie, nie rób tylko squash'a tylko merge commita (tak żeby były widoczne wszystkie commity a nie jeden blob, niestety rebases się nie da zrobić :( ) i najlepiej jak wszystkie joby będą przechodzić, bo z tego co widzę, to coveralls już też jest prawie zielony.

Tak poza tym to powodzenia i dobrej zabawy ;)

**Comment by KrisAphalon** [comment]
Z chęcią zmergowałbym, ale 
![image](https://user-images.githubusercontent.com/25371882/64068534-bbf35780-cc39-11e9-9a05-ea7f8bf8524a.png)
nie mam write accessu ;#

**Comment by akrzyz** [comment]
Dziwne, bo wysłałem Ci zaproszenie w dniu w którym napisałem tamtego posta.
Nie wiem gdzie się one teraz pojawiają, w opcjach mam że zaproszenie jest awaiting response.

**Comment by KrisAphalon** [comment]
Już działa, dzięki.
