### ISSUE TITLE
Zmiana formatu wersji

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#54]
Obecnie wersja dodatku jest hashem ostatniego commita. O wiele ładniej wyglądałoby to, gdyby była ona w formacie human-readable. [Na forku](https://github.com/KrisAphalon/nerthusaddon/blob/gh-pages/version.json) zastosowałem prosty trzystopniowy system: `[ogromne aktualizacje z dużą ilością nowej treści].[dodanie znaczących funkcji].[pomniejsze poprawki] [nazwa aktualizacji]`, gdzie przy pomniejszych poprawkach nazwa się nie zmienia. Tak naprawdę dowolny format byłby dobry, to jest jeden z przykładów jak można to zrobić i jak ja to zaimplementowałem.

Po co ta zmiana? Wersję dodatku widać przy każdym updacie. O wiele łatwiej domyślić się jak wiele zmieniło się od wersji `2.9.3` do wersji `2.9.4` niż z `42880f572ee023da0f662ccb47b7ccf1d297b1f7` do `396cfbcc7d3debd6cf0b5142292994195d516208`. Dodatkowo taka wersja jest łatwiejsza do zapamiętania w razie czyichś problemów z dodatkiem oraz łatwiej posługiwać się takową, np. ogłaszając zmiany na forum czy też na discordzie (a poza tym daje to przyjemne poczucie spełnienia jak przestawia się cyferkę z 9 na 10).

**Comment by akrzyz** [comment]
Tak, tylko w ten sposób straciłeś możliwość wrzucenia na mastera (czy gdzie tam masz postawione github io) nowszej wersji niż jest dostępna graczom. Po to jest hash z cdn po drodze, żeby można było wrzucić nowszą wersje i ją przetestować w grze a dopiero potem podmienić wersje. W tym rozwiązaniu ta możliwość znika.

**Comment by KrisAphalon** [comment]
Testowanie wersji robię (i chyba powinno się robić) na własnym postawionym serwerze, a nie na produkcji. Poza tym można wrzucić zmiany i nie wrzucać nowej wersji, używając `localStorage.NerthusAddonDebug = true` by z githuba pobrało najnowsze zmiany a nie przez cdna.

Wyrzuciłem u siebie cdna bo dużo problemów powodował jak szybko zmieniałem wersje, a jednocześnie nie tak dużo osób z niego korzystało. Nie planuję wyrzucenia go z mastera dla wszystkich. Dlatego jest też na `ghpages` (którego bazą jest `NI`) a nie na `NI`. Na forku NI prawie nie ruszałem startu.

By działało dobrze trzeba dodawać do urlów cdna wersję, bo obecnie dodatek tego nie robi: 
```js
nerthus.addon.fileUrl = function(filename)
{
    return encodeURI([[this.filesPrefix, this.version].join(this.version_separator), filename].join('/'))
}
```
Więc nie dodaje hashu, więc to co mówisz że znika jakaś możliwość nie wiem jak miałoby działać.

**Comment by akrzyz** [comment]
Nie wiem jak chcesz używać CDNa z wersjonowaniem? nie możesz ustawić CDNa po prostu na ghpages czy tam io bo to raz się wczyta i już nigdy wersja w cdnie się nie podmieni bo ciągle będzie wskazywać na ten sam adres niezależnie od wersji.

**Comment by KrisAphalon** [comment]
Dodać hash na koniec cdna który jest wersją z ghpages

czyli
```js
nerthus.addon.fileUrl = function(filename)
{
    return encodeURI([[this.filesPrefix, this.version].join(this.version_separator), filename].join('/') + "?" + nerthus.addon.version)
}
```
I będą wyglądały w mniej więcej ten sposób te wersje: 
`https://glcdn.githack.com/Aphalon/narrator-tools/raw/webpack-test/styles/horizontal.css?version=251`

**Comment by KrisAphalon** [comment]
Można też dodać po prostu nazwę human-readable obok, i chyba tak zrobię.

**Comment by KrisAphalon** [comment]
Dodatek przeniesiony na: https://github.com/nerthus-margonem/nerthusaddon
