### ISSUE TITLE
Zmiana interfejsu testów

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#55]
Obecny [intefejs testów Mocha](https://mochajs.org/#interfaces) (qunit) jest niedorobiony i brakuje mu kilku podstawowych funkcji, takich jak nestowanie kolejnych suitów i before. Do tego sprawia same problemy, jak z wyciekaniem globalnych zmiennych do innych suitów.

Proponuję zmianę interfejsu na taki, który owe funkcje posiada i nie sprawia problemów. Z moich krótkich testów przykładowo [TDD](https://mochajs.org/#tdd) nie wycieka globalnych zmiennych (no bo suiteSetup zamyka już w funkcji), a dodatkowo zawiera nestowanie, a także podobny syntax co qunit (`suite`,`test`) z drobnymi różnicami (`suiteSetup` zamiast `before`, `setup` zamiast `beforeEach`)

Mając wybrać nowy interfejs najbardziej skłaniałbym się właśnie do TDD. Jeżeli jednak będzie taka potrzeba, to mogę się odpowiednio dostosować. Po wybraniu odpowiedniego nowego interfejsu mogę sam przepisać wszystkie testy na niego.

**Comment by KrisAphalon** [comment]
Zmieniłem tu: 7a2b29e 
Od razu testy 10 razy szybciej szybciej lecą.

**Comment by akrzyz** [comment]
Zmiana interfejsu testów spoko, jak ci się takie bardziej podobają to proszę, natomiast nie rozwiązałeś problemu tylko wprowadziłeś na nowo.

Testy lecą szybciej bo wywaliłeś uruchamianie każdego pliku z testami osobno a nie dlatego, że zmieniłeś interfejs testów. Ten interfejs ma dokładnie ten sam problem co poprzedni - globale przeciekają między suite'ami. Global zdefiniowany w jednym z suite'ów jest widoczny w pozostałych co było przyczyną pewnych problemów wcześniej i dlatego zostało to rozdzielone tak, żeby każdy z suite'ów startował z czystym środowiskiem i nie dziedziwczył globali po poprzednich.

**Comment by KrisAphalon** [comment]
Wiem że lecą szybciej bo wywaliłem uruchamianie każdego pliku osobno. Dlatego też to zrobiłem.

Jesteś pewien, że tu też przeciekają?
Jakby przeciekały to by nie działały testy...
[Czy takie zmiany](https://github.com/akrzyz/nerthusaddon/pull/35/commits/0f3eb04a6d352d815e6a308bdb91e4cd4aa194b8) nie powinny w części plików wypisać globala nerthusa przy starcie najwyższego suita (po którym dziedziczą niższe suity, tak jak ma być).
Zamiast tego jest tylko [kilkanaście informacji "No nerthus!"](https://travis-ci.org/akrzyz/nerthusaddon/builds/579165759?utm_source=github_status&utm_medium=notification)

Przecieknął mi tylko global który wcześniej istniał (Date). Dodałem więc `suiteTeardown` by wrócić go do poprzedniej wersji.

Zapewne można by dodać do tego poziom wyżej (przed suiteSetup) ustawianie wszystkich globalów przez `const` czy `let` i by to sprawiło że nie ma żadnej opcji by one przeciekały (function scope, a każdy suite jest w funkcji, przyjemne i logiczne)

**Comment by akrzyz** [comment]
Niestety nie mogę zrobić forka twojego repo jak jest forkiem mojego, a nie chce pchać ci commitów do repo, wrzucam więc diffa który mam na twoim branchu NI.
[am_i_leaking.txt](https://github.com/akrzyz/nerthusaddon/files/3562592/am_i_leaking.txt)
![im_i_leaking](https://user-images.githubusercontent.com/5459551/64066315-4f1b9580-cc18-11e9-8739-0fa41f435a35.png)

Jak widać globale ciekną. Ciekną bo to globale i zachowują się zgodnie z oczekiwaniami jak się nad tym zastanowić. Oczywiście można z uporem maniaka robić wszędzie teardowny do suitów z nadzieją, że się czegoś nie pominie ale to tylko nadzieja. W c++ takie problemy rozwiązuje się za pomocą wrapperów działających w oparciu o RAII ale w js taki koncept jak RAII nie istnieje.

**Comment by KrisAphalon** [comment]
Podmienię część globali które można na consty, a te które muszą być (engine, g) będą teardownowane.
Moim zdaniem to lepsze rozwiązanie niż hackerskie odpalanie każdego pliku z osobna.

**Comment by akrzyz** [comment]
Zwróć uwagę, że są globale, które może stworzyć sam kod a które nie muszą być ustawiane w testach, np. _g jest wrapowane w kilku miejscach w dodatku i zostanie nadpisane czymś nowym nawet jeśli nie istnieje.

**Comment by akrzyz** [comment]
Tak poza tym, to nie wiem po co wyrzucałeś puszczanie tych plików osobno z make, zamiast zrobić nowy target, który będzie puszczał testy tak jak chcesz i jego używać. Jak rozumiem prędkość puszczania testów boli cie lokalnie, bo na travisie to i tak większość czasu zajmuje stawianie środowiska.

**Comment by KrisAphalon** [comment]
Stwierdziłem że robię revert i nie będę się tykał tej beznadziei póki nie przepiszę na webpacka wszystkiego, bo szkoda mojego czasu i nerwów na to,
