### ISSUE TITLE
Zmiany w NN_start należy przerzucić do dodatku ładowanego przy starcie

### ISSUE THREAD

**Issue by KrisAphalon** [akrzyz/nerthusaddon#56]
Obecnie wciąż ładuje się stary, co powoduje błędy jak dodatek próbuje wczytać nowe funkcje logowania. Musiałem dodać [tymczasowego fixa ](https://github.com/akrzyz/nerthusaddon/commit/44efd68f0dce3fb8bd49324da5889dfae62ccdd5), bo inaczej cały dodatek nie będzie działać.

**Comment by akrzyz** [comment]
Zmieniłem start na nowy i zrevertowałem tego fixa.
