### ISSUE TITLE
Add thunders and lightnings to weather

### ISSUE THREAD

**Issue by akrzyz** [akrzyz/nerthusaddon#9]
more info and some graphics at 
https://www.margonem.pl/?task=forum&show=posts&id=264553&ps=5#post40857512
https://www.margonem.pl/?task=forum&show=posts&id=264553&ps=5#post40866371

**Comment by KrisAphalon** [comment]
Pracuję obecnie nad ulepszeniem pogody, także to też zostanie dodane do następnego większego update-a.

**Comment by KrisAphalon** [comment]
Dodatek przeniesiony na: https://github.com/nerthus-margonem/nerthusaddon
(oraz ten feature wprowadzony)
